# PokePy

In [1]:
# Dependencies and Setup

import pandas as pd
import numpy as np
import requests
from pprint import pprint

In [2]:
# Set the API base URL
baseurl = "https://pokeapi.co/api/v2/pokemon/"
poke_requests = requests.get(baseurl).json()
# pprint(poke_requests)

In [3]:
# Set API limits
url = "https://pokeapi.co/api/v2/pokemon/?offset=0&limit=100"
response = requests.get(url).json()
# pprint(response)

# Define an empty list to fetch the poke data 
poke_name = []

poke_results = response["results"]
# pprint(poke_results)

for i in poke_results:
    name = i["name"]
    poke_name.append(name)
# print(poke_name)
print(len(poke_name))

100

In [4]:
# Extract data for metadata
poke_type_1 = []
poke_ids = []
poke_weight = []

for j in poke_name:
    url = baseurl + j
    data_requests = requests.get(url).json()
#     pprint(data_requests)
    
    poke_id = data_requests["id"]
    poke_ids.append(poke_id)
    
    for l in data_requests["types"]:
        if l["slot"] == 1:
            type_1 = l["type"]["name"]
            poke_type_1.append(type_1)
    
    weight = data_requests["weight"]
    poke_weight.append(weight)

In [5]:
metadata_df = pd.DataFrame({
    "name": poke_name,
    "order_id": poke_ids,
    "weight": poke_weight,
    "type_1": poke_type_1})

metadata_df.head()

         name  order_id  weight type_1
0   bulbasaur         1      69  grass
1     ivysaur         2     130  grass
2    venusaur         3    1000  grass
3  charmander         4      85   fire
4  charmeleon         5     190   fire

In [6]:
# Export the Pokemon data into a csv
metadata_df.to_csv("Resources/metadata.csv", index= False)

In [7]:
# Extract data for statistics
hp = []
attack = []
defense = []
sp_attack = []
sp_defense = []
speed = []

for j in poke_name:
    url = baseurl + j
    data_requests = requests.get(url).json()
    
    for p in data_requests["stats"]:
        if p["stat"]["name"] == "hp":
            value = p["base_stat"]
            hp.append(value)
        if p["stat"]["name"] == "attack":
            value = p["base_stat"]
            attack.append(value)
        if p["stat"]["name"] == "defense":
            value = p["base_stat"]
            defense.append(value)
        if p["stat"]["name"] == "special-attack":
            value = p["base_stat"]
            sp_attack.append(value)
        if p["stat"]["name"] == "special-defense":
            value = p["base_stat"]
            sp_defense.append(value)
        if p["stat"]["name"] == "speed":
            value = p["base_stat"]
            speed.append(value)

In [8]:
statistics_df = pd.DataFrame({
    "name": poke_name,
    "order_id": poke_ids,
    "hp" : hp,
    "attack" : attack,
    "defense": defense, 
    "special_attack": sp_attack,
    "special_defense": sp_defense,
    "speed": speed})

statistics_df.head()

,name,order_id,hp,attack,defense,special_attack,special_defense,speed
0,bulbasaur,1,45,49,49,65,65,45
1,ivysaur,2,60,62,63,80,80,60
2,venusaur,3,80,82,83,100,100,80
3,charmander,4,39,52,43,60,50,65
4,charmeleon,5,58,64,58,80,65,80

In [9]:
# Export the Pokemon Data into a csv
statistics_df.to_csv("Resources/statistics.csv", index= False)

In [10]:
# Extract data for pictures
pics_default = []
pics_shiny = []

for j in poke_name:
    url = baseurl + j
    data_requests = requests.get(url).json()
    
    pic_default = data_requests["sprites"]["other"]["official-artwork"]["front_default"]
    pics_default.append(pic_default)
    
    pic_shiny = data_requests["sprites"]["other"]["home"]["front_shiny"]
    pics_shiny.append(pic_shiny)

In [11]:
sprites_df = pd.DataFrame({
        "name": poke_name,
        "order_id": poke_ids,
        "sprites_default": pics_default,
        "sprites_shiny": pics_shiny})
sprites_df.head()

,name,order_id,sprites_default,sprites_shiny
0,bulbasaur,1,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...
1,ivysaur,2,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...
2,venusaur,3,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...
3,charmander,4,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...
4,charmeleon,5,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...

In [12]:
# Export the Pokemon Data into a csv
sprites_df.to_csv("Resources/sprites.csv", index= False)